import { useState } from 'react';
import { ArrowLeft, Check, ChevronDown, RotateCcw, X } from 'lucide-react';
import { motion } from 'motion/react';
import { generateQuiz, judgeAnswer } from '../data/quizEngine';
import type { QuizDirection, QuizItem, QuizResult, ViewState } from '../data/types';
interface Props { direction: QuizDirection; wordId?: string; navigate:(view:ViewState)=>void; }
export function QuizView({ direction, wordId, navigate }: Props) {
 const [items,setItems]=useState<QuizItem[]>(()=>generateQuiz(direction,wordId)); const [index,setIndex]=useState(0); const [input,setInput]=useState(''); const [result,setResult]=useState<QuizResult|null>(null); const [answers,setAnswers]=useState<QuizResult[]>([]); const [showReview,setShowReview]=useState(false);
 const done=answers.length===items.length; const item=items[index]; const reset=()=>{setItems(generateQuiz(direction,wordId));setIndex(0);setInput('');setResult(null);setAnswers([]);setShowReview(false);}; const back=()=>navigate(wordId?{name:'wordDetail',wordId}:{name:'training'});
 if(done) { const correct=answers.filter(a=>a.correct).length; return <main style={{minHeight:'100vh',padding:'52px 24px 112px',background:'#F7F9FC'}}><button onClick={back} style={backStyle}><ArrowLeft size={18}/> 返回</button><section style={{marginTop:28,background:'#fff',borderRadius:24,padding:'30px 24px',boxShadow:'0 8px 28px rgba(25,49,80,.06)',textAlign:'center'}}><p style={{margin:0,color:'#2563EB',fontSize:12,fontWeight:700,letterSpacing:1.5}}>本轮完成</p><div style={{fontSize:48,fontWeight:760,color:'#111827',margin:'14px 0 4px',letterSpacing:'-1px'}}>{correct}<span style={{fontSize:20,color:'#9CA3AF',fontWeight:500}}> / {items.length}</span></div><p style={{margin:0,color:'#6B7280',fontSize:14}}>正确率 {Math.round(correct/items.length*100)}%</p></section><button onClick={()=>setShowReview(!showReview)} style={{...plainButton,width:'100%',marginTop:16,justifyContent:'space-between',background:'#fff',borderRadius:18,padding:'17px 18px',boxShadow:'0 3px 14px rgba(25,49,80,.04)'}}>逐题回顾 <ChevronDown size={18} style={{transform:showReview?'rotate(180deg)':'none'}}/></button>{showReview&&<div style={{marginTop:10,display:'grid',gap:8}}>{answers.map((answer,i)=><div key={i} style={{padding:'14px 16px',borderRadius:14,background:answer.correct?'#F0FDF4':'#FFF1F2',color:answer.correct?'#166534':'#9F1239',fontSize:13,display:'flex',gap:10,alignItems:'center'}}>{answer.correct?<Check size={16}/>:<X size={16}/>}第 {i+1} 题 · {answer.score} 分</div>)}</div>}<button onClick={reset} style={{...primaryButton,marginTop:24}}><RotateCcw size={18}/>再来一组</button></main>; }
 const submit=()=>{if(!result){const judged=judgeAnswer(item,input,direction);setResult(judged);}else{setAnswers(a=>[...a,result]);setIndex(i=>i+1);setInput('');setResult(null);}};
 return <main style={{minHeight:'100vh',padding:'48px 24px 112px',background:'#F7F9FC'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><button onClick={back} style={backStyle}><ArrowLeft size={18}/> 返回</button><span style={{fontSize:13,color:'#6B7280'}}>{index+1} / {items.length}</span></div><div style={{height:4,background:'#E8EDF4',borderRadius:9,margin:'18px 0 28px',overflow:'hidden'}}><div style={{height:'100%',width:`${((index+1)/items.length)*100}%`,background:'#2563EB',borderRadius:9,transition:'width .3s'}}/></div><section style={{background:'#fff',borderRadius:24,padding:24,boxShadow:'0 8px 28px rgba(25,49,80,.06)'}}><p style={{margin:'0 0 14px',fontSize:11,fontWeight:700,color:'#9CA3AF',letterSpacing:1.4}}>翻译成英语</p><h1 style={{margin:'0 0 22px',fontSize:23,lineHeight:1.55,color:'#111827',fontWeight:700}}>{item.prompt}</h1><span style={{display:'inline-block',padding:'6px 10px',borderRadius:9,background:'#F1F5F9',color:'#64748B',fontSize:12}}>{item.hint}</span></section><textarea disabled={!!result} value={input} onChange={e=>setInput(e.target.value)} placeholder="输入你的英文表达…" style={{width:'100%',boxSizing:'border-box',minHeight:130,resize:'vertical',marginTop:16,border:`1.5px solid ${result?'#E5E7EB':'#DCE3EC'}`,borderRadius:16,padding:16,background:result?'#F8FAFC':'#fff',fontFamily:'inherit',fontSize:16,lineHeight:1.65,color:'#111827',outline:'none'}} />{result&&<motion.section initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} style={{marginTop:16,borderRadius:18,padding:18,background:result.correct?'#F0FDF4':'#FFF1F2',color:result.correct?'#166534':'#9F1239'}}><div style={{display:'flex',gap:9,alignItems:'center',fontSize:15,fontWeight:700}}>{result.correct?<Check size={18}/>:<X size={18}/>} {result.correct?'表达正确':'再调整一下'}</div><p style={{margin:'11px 0 0',fontSize:13,lineHeight:1.7}}>{result.analysis}</p></motion.section>}<button onClick={submit} style={{...primaryButton,marginTop:20}}>{result?(index===items.length-1?'查看结果':'下一题'):'提交'}</button></main>;
}
const backStyle={display:'inline-flex',alignItems:'center',gap:6,border:0,background:'transparent',color:'#6B7280',cursor:'pointer',padding:0,fontSize:14};
const primaryButton={display:'flex',alignItems:'center',justifyContent:'center',gap:8,width:'100%',height:52,border:0,borderRadius:16,background:'#2563EB',color:'#fff',cursor:'pointer',fontSize:15,fontWeight:650,boxShadow:'0 8px 18px rgba(37,99,235,.2)'};
const plainButton={display:'inline-flex',alignItems:'center',gap:8,border:0,background:'transparent',color:'#475569',cursor:'pointer',padding:8,fontSize:14};
